Repository 7JEON8KI/backend, pull requests merged in 2024-02, with the labels that each got.

#1 Feat: project init & login
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  pom.xml
  src/main/java/com/hyundai/config/ApplicationProperties.java
  src/main/java/com/hyundai/config/PropertyConfig.java
  src/main/java/com/hyundai/config/WebMvcConfig.java
  src/main/java/com/hyundai/login/controller/AdminController.java
  src/main/java/com/hyundai/login/controller/AuthController.java
  src/main/java/com/hyundai/login/domain/Member.java
  src/main/java/com/hyundai/login/domain/enumtype/OauthProvider.java
  src/main/java/com/hyundai/login/domain/enumtype/Role.java
  src/main/java/com/hyundai/login/dto/Criteria.java
  src/main/java/com/hyundai/login/dto/MemberDto.java
  src/main/java/com/hyundai/login/dto/MemberListDto.java
  src/main/java/com/hyundai/login/dto/criteria/MemberCriteria.java
  src/main/java/com/hyundai/login/mapper/MemberMapper.java
  src/main/java/com/hyundai/login/security/JwtInterceptor.java
  src/main/java/com/hyundai/login/security/JwtResolver.java
  src/main/java/com/hyundai/login/security/JwtTokenProvider.java
  src/main/java/com/hyundai/login/security/KakaoOauthClient.java
  src/main/java/com/hyundai/login/security/dto/KakaoOauthTokenDto.java
  src/main/java/com/hyundai/login/security/dto/KakaoTokens.java
  src/main/java/com/hyundai/login/security/dto/KakaoUserInfoDto.java
  src/main/java/com/hyundai/login/security/dto/LoginRequestDto.java
  src/main/java/com/hyundai/login/security/dto/LoginResponseDto.java
  src/main/java/com/hyundai/login/security/dto/OAuthType.java
  src/main/java/com/hyundai/login/security/dto/TokenDto.java
  src/main/java/com/hyundai/login/service/AuthService.java
  src/main/java/com/hyundai/login/service/MemberService.java
  src/main/resources/com/hyundai/mapper/MemberMapper.xml
  src/main/resources/config.properties
  src/main/resources/log4j.xml
  src/main/webapp/META-INF/context.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/web.xml
  src/test/java/com/hyundai/controller/MemberControllerTests.java
  src/test/java/jdbc/DataSourceTests.java
  src/test/java/jdbc/JDBCTest.java
  src/test/resources/log4j.xml
Labels: feature

#5 상품 리스트 조회, 상품 상세 조회 초안
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
  src/main/java/com/hyundai/domain/product/dto/request/ProductRequestDTO.java
  src/main/java/com/hyundai/domain/product/dto/response/ProductResposneDTO.java
  src/main/java/com/hyundai/domain/product/entity/Product.java
  src/main/java/com/hyundai/domain/product/service/GetProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/global/exception/GlobalErrorCode.java
  src/main/java/com/hyundai/global/exception/GlobalException.java
  src/main/java/com/hyundai/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hyundai/global/mapper/ProductMapper.java
  src/main/java/com/hyundai/global/message/ResponseMessage.java
  src/main/resources/com/hyundai/global/mapper/ProductMapper.xml
Labels: feature, 🍔 소민

#8 결제 기능 초안 작성
  pom.xml
  src/main/java/com/hyundai/domain/orderProduct/controller/OrderProductController.java
  src/main/java/com/hyundai/domain/orderProduct/dto/PaymentInfoDTO.java
  src/main/java/com/hyundai/domain/orderProduct/entity/OrderProduct.java
  src/main/java/com/hyundai/domain/orders/controller/OrderController.java
  src/main/java/com/hyundai/domain/orders/dto/OrderInfo.java
  src/main/java/com/hyundai/domain/orders/dto/OrderSaveDTO.java
  src/main/java/com/hyundai/domain/orders/entity/Orders.java
  src/main/java/com/hyundai/domain/orders/service/OrderService.java
  src/main/java/com/hyundai/domain/payment/controller/PaymentController.java
  src/main/java/com/hyundai/domain/payment/entity/enums/IamportApiURL.java
  src/main/java/com/hyundai/domain/payment/entity/enums/PayStatus.java
  src/main/java/com/hyundai/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/hyundai/domain/payment/service/RefundService.java
  src/main/java/com/hyundai/domain/payment/service/RefundServiceImpl.java
  src/main/java/com/hyundai/global/config/ApplicationProperties.java
  src/main/java/com/hyundai/global/config/TemplateConfig.java
  src/main/java/com/hyundai/global/exception/GlobalErrorCode.java
  src/main/java/com/hyundai/global/mapper/OrderMapper.java
  src/main/java/com/hyundai/global/mapper/OrderProductMapper.java
  src/main/java/com/hyundai/global/mapper/ProductMapper.java
  src/main/resources/com/hyundai/global/mapper/OrderMapper.xml
  src/main/resources/com/hyundai/global/mapper/OrderProductMapper.xml
  src/main/resources/com/hyundai/global/mapper/ProductMapper.xml
  src/main/resources/config.properties
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/web.xml
Labels: feature, 🍔 소민

#10 찜 기능 구현
  src/main/java/com/hyundai/domain/like/controller/LikeController.java
  src/main/java/com/hyundai/domain/like/dto/LikeProductDto.java
  src/main/java/com/hyundai/domain/like/dto/LikeProductListResponseDto.java
  src/main/java/com/hyundai/domain/like/entity/Like.java
  src/main/java/com/hyundai/domain/like/service/LikeService.java
  src/main/java/com/hyundai/domain/like/service/LikeServiceImpl.java
  src/main/java/com/hyundai/global/mapper/LikeMapper.java
  src/main/resources/com/hyundai/global/mapper/LikeMapper.xml
Labels: feature, 🐥형준

#12 장바구니 API 추가, 삭제, 수정, 전체 및 수량 조회
  src/main/java/com/hyundai/domain/cart/controller/CartController.java
  src/main/java/com/hyundai/domain/cart/dto/CartProductDto.java
  src/main/java/com/hyundai/domain/cart/dto/request/CartProductRequestDto.java
  src/main/java/com/hyundai/domain/cart/dto/response/CartListResponseDto.java
  src/main/java/com/hyundai/domain/cart/entity/Cart.java
  src/main/java/com/hyundai/domain/cart/entity/CartProduct.java
  src/main/java/com/hyundai/domain/cart/service/CartService.java
  src/main/java/com/hyundai/domain/cart/service/CartServiceImpl.java
  src/main/java/com/hyundai/global/mapper/CartMapper.java
  src/main/resources/com/hyundai/global/mapper/CartMapper.xml
Labels: feature, 🐥형준

#13 swagger 적용
  pom.xml
  src/main/java/com/hyundai/global/config/SwaggerConfig.java
  src/main/java/com/hyundai/global/config/WebMvcConfig.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: feature, 🐥형준

#14 관리자 회원 코드 업데이트, S3 추가
  pom.xml
  src/main/java/com/hyundai/domain/admin/Enum/Standard.java
  src/main/java/com/hyundai/domain/admin/controller/AdminController.java
  src/main/java/com/hyundai/domain/admin/dto/AdminMemberDTO.java
  src/main/java/com/hyundai/domain/admin/dto/AdminMemberParamDTO.java
  src/main/java/com/hyundai/domain/admin/service/AdminService.java
  src/main/java/com/hyundai/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/hyundai/domain/login/dto/Criteria.java
  src/main/java/com/hyundai/domain/login/dto/criteria/MemberCriteria.java
  src/main/java/com/hyundai/domain/utils/file/AwsS3Util.java
  src/main/java/com/hyundai/domain/utils/file/DownExcelView.java
  src/main/java/com/hyundai/domain/utils/file/FileUploadController.java
  src/main/java/com/hyundai/domain/utils/paging/Criteria.java
  src/main/java/com/hyundai/domain/utils/paging/PageDTO.java
  src/main/java/com/hyundai/global/config/ApplicationProperties.java
  src/main/java/com/hyundai/global/config/S3Config.java
  src/main/java/com/hyundai/global/exception/GlobalErrorCode.java
  src/main/java/com/hyundai/global/interceptor/TokenInterceptor.java
  src/main/java/com/hyundai/global/mapper/AdminMapper.java
  src/main/resources/com/hyundai/global/mapper/AdminMapper.xml
  src/main/resources/config.properties
  src/main/resources/log4j.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: feature, :1st_place_medal: 은구

#15 리뷰 API
  pom.xml
  src/main/java/com/hyundai/domain/review/controller/ReviewController.java
  src/main/java/com/hyundai/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/com/hyundai/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/hyundai/domain/review/entity/Review.java
  src/main/java/com/hyundai/domain/review/entity/enumType/ReviewGetType.java
  src/main/java/com/hyundai/domain/review/entity/enumType/ReviewOperatation.java
  src/main/java/com/hyundai/domain/review/service/ReviewService.java
  src/main/java/com/hyundai/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/hyundai/global/exception/GlobalErrorCode.java
  src/main/java/com/hyundai/global/mapper/ReviewMapper.java
  src/main/resources/com/hyundai/global/mapper/ReviewMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: feature, 🐥형준

#17 API 수정
  src/main/java/com/hyundai/domain/cart/service/CartServiceImpl.java
  src/main/java/com/hyundai/domain/like/controller/LikeController.java
  src/main/java/com/hyundai/domain/like/service/LikeServiceImpl.java
  src/main/java/com/hyundai/domain/login/service/oauth/RequestOAuthInfoService.java
  src/main/java/com/hyundai/domain/orderProduct/controller/OrderProductController.java
  src/main/java/com/hyundai/domain/orders/controller/OrderController.java
  src/main/java/com/hyundai/domain/payment/controller/PaymentController.java
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/domain/utils/file/AwsS3Util.java
  src/main/java/com/hyundai/domain/utils/file/DownExcelView.java
  src/main/java/com/hyundai/domain/utils/file/FileUploadController.java
Labels: 🐥형준, fix

#18 Products API 리팩토링
  src/main/java/com/hyundai/domain/cart/dto/CartProductDto.java
  src/main/java/com/hyundai/domain/like/dto/LikeProductDto.java
  src/main/java/com/hyundai/domain/login/security/JwtFilter.java
  src/main/java/com/hyundai/domain/login/security/JwtResultType.java
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
  src/main/java/com/hyundai/domain/product/dto/response/ProductResponseDTO.java
  src/main/java/com/hyundai/domain/product/entity/Product.java
  src/main/java/com/hyundai/domain/product/service/GetProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/global/config/SecurityConfig.java
  src/main/java/com/hyundai/global/config/WebMvcConfig.java
  src/main/java/com/hyundai/global/mapper/ProductMapper.java
  src/main/resources/com/hyundai/global/mapper/CartMapper.xml
  src/main/resources/com/hyundai/global/mapper/LikeMapper.xml
  src/main/resources/com/hyundai/global/mapper/ProductMapper.xml
Labels: feature, 🐥형준

#20 상품 관련 관리자/판매자 API
  pom.xml
  src/main/java/com/hyundai/domain/admin/controller/AdminProductController.java
  src/main/java/com/hyundai/domain/admin/dto/AdminProductDTO.java
  src/main/java/com/hyundai/domain/admin/dto/AdminProductIngredientDTO.java
  src/main/java/com/hyundai/domain/admin/dto/AdminProductParamDTO.java
  src/main/java/com/hyundai/domain/admin/dto/AdminThemeDTO.java
  src/main/java/com/hyundai/domain/admin/service/AdminProductService.java
  src/main/java/com/hyundai/domain/admin/service/AdminProductServiceImpl.java
  src/main/java/com/hyundai/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/hyundai/domain/login/service/oauth/OAuthServiceImpl.java
  src/main/java/com/hyundai/domain/manager/controller/ManagerProductController.java
  src/main/java/com/hyundai/domain/manager/dto/ManagerOrderDTO.java
  src/main/java/com/hyundai/domain/manager/dto/ManagerOrderProductDTO.java
  src/main/java/com/hyundai/domain/manager/dto/ManagerProductAddSubDTO.java
  src/main/java/com/hyundai/domain/manager/dto/ManagerProductDTO.java
  src/main/java/com/hyundai/domain/manager/service/ManagerProductService.java
  src/main/java/com/hyundai/domain/manager/service/ManagerProductServiceImpl.java
  src/main/java/com/hyundai/global/config/SecurityConfig.java
  src/main/java/com/hyundai/global/exception/GlobalErrorCode.java
  src/main/java/com/hyundai/global/mapper/AdminMapper.java
  src/main/java/com/hyundai/global/mapper/AdminProductMapper.java
  src/main/java/com/hyundai/global/mapper/ManagerMapper.java
  src/main/resources/com/hyundai/global/mapper/AdminProductMapper.xml
  src/main/resources/com/hyundai/global/mapper/ManagerMapper.xml
  src/main/resources/com/hyundai/global/mapper/MemberMapper.xml
  src/main/resources/log4j.xml
Labels: feature, :1st_place_medal: 은구

#19 Cors 에러 해결
  src/main/java/com/hyundai/global/config/CorsConfig.java
  src/main/java/com/hyundai/global/config/SecurityConfig.java
  src/main/resources/com/hyundai/global/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/web.xml
Labels: 🐥형준, fix

#22 ElasticSearch 초안 구현
  pom.xml
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
  src/main/java/com/hyundai/domain/product/dto/request/SearchRequestDTO.java
  src/main/java/com/hyundai/domain/product/entity/Product.java
  src/main/java/com/hyundai/domain/product/repository/ProductSearchRepository.java
  src/main/java/com/hyundai/domain/product/service/ProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/hyundai/global/config/ElasticSearchConfig.java
  src/main/java/com/hyundai/global/config/TemplateConfig.java
  src/main/java/com/hyundai/global/mapper/ProductMapper.java
  src/main/resources/config.properties
  src/main/resources/log4j2.xml
Labels: feature, 🍔 소민

#21 관리자 이벤트/배너(CRUD) API 추가, Admin 폴더 구조 획일
  pom.xml
  src/main/java/com/hyundai/domain/admin/controller/AdminBannerController.java
  src/main/java/com/hyundai/domain/admin/controller/AdminController.java
  src/main/java/com/hyundai/domain/admin/controller/AdminEventController.java
  src/main/java/com/hyundai/domain/admin/controller/AdminMemberController.java
  src/main/java/com/hyundai/domain/admin/controller/AdminProductController.java
  src/main/java/com/hyundai/domain/admin/dto/AdminBannerDTO.java
  src/main/java/com/hyundai/domain/admin/dto/AdminEventDTO.java
  src/main/java/com/hyundai/domain/admin/dto/AdminProductDTO.java
  src/main/java/com/hyundai/domain/admin/service/AdminBannerService.java
  src/main/java/com/hyundai/domain/admin/service/AdminBannerServiceImpl.java
  src/main/java/com/hyundai/domain/admin/service/AdminEventService.java
  src/main/java/com/hyundai/domain/admin/service/AdminEventServiceImpl.java
  src/main/java/com/hyundai/domain/admin/service/AdminMemberService.java
  src/main/java/com/hyundai/domain/admin/service/AdminMemberServiceImpl.java
  src/main/java/com/hyundai/domain/admin/service/AdminProductService.java
  src/main/java/com/hyundai/global/mapper/AdminBannerMapper.java
  src/main/java/com/hyundai/global/mapper/AdminEventMapper.java
  src/main/java/com/hyundai/global/mapper/AdminMemberMapper.java
  src/main/resources/com/hyundai/global/mapper/AdminBannerMapper.xml
  src/main/resources/com/hyundai/global/mapper/AdminEventMapper.xml
  src/main/resources/com/hyundai/global/mapper/AdminMemberMapper.xml
  src/main/resources/com/hyundai/global/mapper/ManagerMapper.xml
Labels: feature, :1st_place_medal: 은구

#23 recommendation 기능 구현
  src/main/java/com/hyundai/domain/login/security/JwtFilter.java
  src/main/java/com/hyundai/domain/product/dto/request/ProductRequestDTO.java
  src/main/java/com/hyundai/domain/product/dto/response/RecommendProducts.java
  src/main/java/com/hyundai/domain/product/entity/Product.java
  src/main/java/com/hyundai/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/hyundai/global/config/SecurityConfig.java
Labels: feature, 🍔 소민

#24 redis cache 적용
  pom.xml
  src/main/java/com/hyundai/domain/like/service/LikeServiceImpl.java
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
  src/main/java/com/hyundai/domain/product/service/ProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/global/config/ApplicationProperties.java
  src/main/java/com/hyundai/global/config/JacksonConfig.java
  src/main/java/com/hyundai/global/config/RedisConfig.java
  src/main/resources/config.properties
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: feature, 🍔 소민

#25 feat: 상품 조회 페이지네이션 / 정렬
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
  src/main/java/com/hyundai/domain/product/dto/request/ProductCriteria.java
  src/main/java/com/hyundai/domain/product/dto/request/WrapperSearchDTO.java
  src/main/java/com/hyundai/domain/product/dto/response/ProductResponseDTO.java
  src/main/java/com/hyundai/domain/product/service/ProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/global/mapper/ProductMapper.java
  src/main/resources/com/hyundai/global/mapper/ProductMapper.xml
Labels: feature, 🐥형준

#26 fix: cart 프로시져 수정
  src/main/resources/com/hyundai/global/mapper/CartMapper.xml
Labels: bug, 🐥형준, fix

#27 payment refactoring
  src/main/java/com/hyundai/domain/orderProduct/entity/OrderProduct.java
  src/main/java/com/hyundai/domain/orders/controller/OrderController.java
  src/main/java/com/hyundai/domain/orders/dto/OrderSaveDTO.java
  src/main/java/com/hyundai/domain/orders/entity/Orders.java
  src/main/java/com/hyundai/domain/payment/controller/PaymentController.java
  src/main/java/com/hyundai/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/hyundai/global/mapper/OrderProductMapper.java
  src/main/resources/com/hyundai/global/mapper/OrderMapper.xml
  src/main/resources/com/hyundai/global/mapper/OrderProductMapper.xml
Labels: feature, 🍔 소민

#28 fix: 메소드 POST로 변경
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
Labels: bug, 🐥형준, fix

#29 전체 리뷰 페이지네이션
  src/main/java/com/hyundai/domain/review/controller/ReviewController.java
  src/main/java/com/hyundai/domain/review/service/ReviewService.java
  src/main/java/com/hyundai/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/hyundai/global/config/SecurityConfig.java
  src/main/java/com/hyundai/global/mapper/ReviewMapper.java
  src/main/resources/com/hyundai/global/mapper/ReviewMapper.xml
Labels: feature, 🐥형준

#30 와인 추천 기능 초안
  src/main/java/com/hyundai/domain/product/dto/request/ProductRequestDTO.java
  src/main/java/com/hyundai/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/hyundai/domain/recommendation/service/RecommendationService.java
  src/main/java/com/hyundai/domain/recommendation/service/RecommendationServiceImpl.java
  src/main/java/com/hyundai/global/config/ElasticSearchConfig.java
  src/main/java/com/hyundai/global/mapper/ProductMapper.java
  src/main/resources/com/hyundai/global/mapper/ProductMapper.xml
Labels: feature, 🍔 소민

#32 멤버 정보 조회 및 수정
  src/main/java/com/hyundai/domain/login/controller/AuthController.java
  src/main/java/com/hyundai/domain/login/dto/MemberInfoRequestDto.java
  src/main/java/com/hyundai/domain/login/dto/MemberInfoResponseDto.java
  src/main/java/com/hyundai/domain/login/service/oauth/OAuthService.java
  src/main/java/com/hyundai/domain/login/service/oauth/OAuthServiceImpl.java
  src/main/java/com/hyundai/global/mapper/MemberMapper.java
  src/main/resources/com/hyundai/global/mapper/MemberMapper.xml
Labels: feature, 🐥형준

#31 와인 및 테마 상품 리스트 조회
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
  src/main/java/com/hyundai/domain/product/service/ProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/global/mapper/ProductMapper.java
  src/main/resources/com/hyundai/global/mapper/ProductMapper.xml
Labels: feature, 🐥형준
