Repository 7JEON8KI/backend, pull requests merged in 2024-03, with the labels that each got.

#35 로그 필터 memberId 예외처리
  src/main/java/com/hyundai/global/filter/LogFilter.java
Labels: fix

#36 로그 필터 request 복제 및 전송
  src/main/java/com/hyundai/global/filter/LogFilter.java
Labels: feature, :1st_place_medal: 은구

#37 fix: 스웨거 헤더 붙이기
  src/main/java/com/hyundai/global/config/SwaggerConfig.java
Labels: bug, 🐥형준, fix

#38 서버간 요청 LOG 제외
  src/main/java/com/hyundai/global/filter/LogFilter.java
  src/main/resources/com/hyundai/global/mapper/LogMapper.xml
Labels: :1st_place_medal: 은구, fix

#33 쿠폰 API: 유저가 가진 쿠폰 리스트 조회
  src/main/java/com/hyundai/domain/coupon/controller/CouponController.java
  src/main/java/com/hyundai/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/hyundai/domain/coupon/entity/Coupon.java
  src/main/java/com/hyundai/domain/coupon/service/CouponService.java
  src/main/java/com/hyundai/domain/coupon/service/CouponServiceImpl.java
  src/main/java/com/hyundai/global/mapper/CouponMapper.java
  src/main/resources/com/hyundai/global/mapper/CouponMapper.xml
Labels: feature, 🏋️‍♀️지윤

#40 fix: 찜 목록 조회 시 null 수정
  src/main/resources/com/hyundai/global/mapper/LikeMapper.xml
Labels: bug, 🐥형준, fix

#41 주문내역 조회 및 리뷰 작성이 가능한 목록 조회
  src/main/java/com/hyundai/domain/orders/controller/OrderController.java
  src/main/java/com/hyundai/domain/orders/dto/OrderProductDto.java
  src/main/java/com/hyundai/domain/orders/dto/OrderResponseDto.java
  src/main/java/com/hyundai/domain/orders/service/OrderService.java
  src/main/java/com/hyundai/domain/review/controller/ReviewController.java
  src/main/java/com/hyundai/domain/review/dto/response/AbleReviewProductResponseDto.java
  src/main/java/com/hyundai/domain/review/service/ReviewService.java
  src/main/java/com/hyundai/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/hyundai/global/mapper/OrderMapper.java
  src/main/java/com/hyundai/global/mapper/ReviewMapper.java
  src/main/resources/com/hyundai/global/mapper/OrderMapper.xml
  src/main/resources/com/hyundai/global/mapper/ReviewMapper.xml
Labels: feature, 🐥형준

#42 이미지 검색 백엔드 구현
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
  src/main/java/com/hyundai/domain/product/dto/request/WrapperSearchDTO.java
  src/main/java/com/hyundai/domain/product/service/ProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
Labels: feature, 🍔 소민

#44 s3-파일 저장 주소 변경, 배너 조회 api
  src/main/java/com/hyundai/domain/admin/controller/AdminProductController.java
  src/main/java/com/hyundai/domain/user/controller/UserController.java
  src/main/java/com/hyundai/domain/user/service/UserService.java
  src/main/java/com/hyundai/domain/utils/file/AwsS3Util.java
  src/main/java/com/hyundai/domain/utils/file/FileUploadController.java
  src/main/java/com/hyundai/global/config/SecurityConfig.java
  src/main/java/com/hyundai/global/filter/LogFilter.java
  src/main/java/com/hyundai/global/mapper/AdminProductMapper.java
  src/main/resources/com/hyundai/global/mapper/AdminProductMapper.xml
Labels: feature, :1st_place_medal: 은구, fix

#45 페이징 토탈 개수 / pageAmount 입력가능
  src/main/java/com/hyundai/domain/product/dto/response/ProductTotalDTO.java
  src/main/java/com/hyundai/domain/product/dto/response/ProductWithCountResponseDTO.java
  src/main/java/com/hyundai/domain/product/service/ProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/global/mapper/ProductMapper.java
  src/main/resources/com/hyundai/global/mapper/ProductMapper.xml
Labels: 🐥형준, fix

#46 주문내역 상세조회
  src/main/java/com/hyundai/domain/orders/controller/OrderController.java
  src/main/java/com/hyundai/domain/orders/service/OrderService.java
  src/main/java/com/hyundai/global/mapper/OrderMapper.java
  src/main/resources/com/hyundai/global/mapper/OrderMapper.xml
Labels: feature, 🐥형준

#47 리뷰 내역 조회 상품 정보 join
  src/main/java/com/hyundai/domain/review/dto/response/MyReviewResponseDto.java
  src/main/java/com/hyundai/domain/review/service/ReviewService.java
  src/main/java/com/hyundai/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/hyundai/global/mapper/ReviewMapper.java
  src/main/resources/com/hyundai/global/mapper/ReviewMapper.xml
Labels: 🐥형준, fix

#49 fix: 사진 시큐리티 & 장바구니 사진 오류
  src/main/java/com/hyundai/global/config/SecurityConfig.java
  src/main/resources/com/hyundai/global/mapper/CartMapper.xml
Labels: bug, 🐥형준, fix

#50 배너 조회시 사용 기간 확인 추가
  src/main/java/com/hyundai/domain/admin/controller/AdminProductController.java
  src/main/java/com/hyundai/domain/admin/dto/AdminProductDTO.java
  src/main/java/com/hyundai/domain/admin/service/AdminProductService.java
  src/main/java/com/hyundai/domain/admin/service/AdminProductServiceImpl.java
  src/main/java/com/hyundai/domain/user/service/UserService.java
  src/main/java/com/hyundai/global/mapper/AdminProductMapper.java
  src/main/java/com/hyundai/global/mapper/UserMapper.java
  src/main/resources/com/hyundai/global/mapper/AdminProductMapper.xml
  src/main/resources/com/hyundai/global/mapper/UserMapper.xml
Labels: :1st_place_medal: 은구, fix

#51 fix: 리뷰 404 오류 204로 수정
  src/main/java/com/hyundai/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/hyundai/global/exception/GlobalErrorCode.java
Labels: bug, 🐥형준, fix

#54 백엔드 API 디테일 수정 및 변경 추가
  src/main/java/com/hyundai/domain/admin/controller/AdminBannerController.java
  src/main/java/com/hyundai/domain/admin/service/AdminBannerService.java
  src/main/java/com/hyundai/domain/admin/service/AdminBannerServiceImpl.java
  src/main/java/com/hyundai/domain/admin/service/AdminMemberServiceImpl.java
  src/main/java/com/hyundai/domain/manager/controller/ManagerProductController.java
  src/main/java/com/hyundai/domain/manager/dto/ManagerOrderProductDTO.java
  src/main/java/com/hyundai/domain/manager/service/ManagerProductService.java
  src/main/java/com/hyundai/domain/manager/service/ManagerProductServiceImpl.java
  src/main/java/com/hyundai/global/mapper/AdminBannerMapper.java
  src/main/java/com/hyundai/global/mapper/AdminMemberMapper.java
  src/main/java/com/hyundai/global/mapper/ManagerMapper.java
  src/main/resources/com/hyundai/global/mapper/AdminBannerMapper.xml
  src/main/resources/com/hyundai/global/mapper/AdminMemberMapper.xml
  src/main/resources/com/hyundai/global/mapper/AdminProductMapper.xml
  src/main/resources/com/hyundai/global/mapper/ManagerMapper.xml
Labels: :1st_place_medal: 은구, fix

#55 판매자 대쉬보드 Top 조회 쿼리 작성
  src/main/java/com/hyundai/domain/admin/controller/AdminProductController.java
  src/main/java/com/hyundai/domain/manager/controller/ManagerProductController.java
  src/main/java/com/hyundai/domain/manager/dto/ManagerTop5ProductDTO.java
  src/main/java/com/hyundai/domain/manager/service/ManagerProductService.java
  src/main/java/com/hyundai/domain/manager/service/ManagerProductServiceImpl.java
  src/main/java/com/hyundai/global/mapper/ManagerMapper.java
  src/main/resources/com/hyundai/global/mapper/ManagerMapper.xml
Labels: feature, :1st_place_medal: 은구

#57 fix: 검색 기능 리팩토링
  src/main/java/com/hyundai/domain/product/dto/IngredientExpansion.java
  src/main/java/com/hyundai/domain/product/repository/ProductSearchRepository.java
Labels: 🍔 소민, fix

#58 feat: 식재료 가져오기
  src/main/java/com/hyundai/domain/login/security/JwtFilter.java
  src/main/java/com/hyundai/domain/product/controller/ProductController.java
  src/main/java/com/hyundai/domain/product/dto/response/IngredientDTO.java
  src/main/java/com/hyundai/domain/product/service/ProductService.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/global/config/SecurityConfig.java
  src/main/java/com/hyundai/global/mapper/ProductMapper.java
  src/main/resources/com/hyundai/global/mapper/ProductMapper.xml
Labels: feature, 🐥형준

#60 Feat/excel 기능 추가
  src/main/java/com/hyundai/domain/manager/controller/ManagerProductController.java
  src/main/java/com/hyundai/domain/manager/dto/ManagerProductDTO.java
  src/main/java/com/hyundai/domain/manager/service/ManagerProductService.java
  src/main/java/com/hyundai/domain/manager/service/ManagerProductServiceImpl.java
  src/main/java/com/hyundai/domain/product/service/ProductServiceImpl.java
  src/main/java/com/hyundai/domain/utils/dto/OrderListDeliveryDTO.java
  src/main/java/com/hyundai/domain/utils/file/DownExcelView.java
  src/main/java/com/hyundai/global/mapper/ExcelMapper.java
  src/main/resources/com/hyundai/global/mapper/ExcelMapper.xml
  src/main/resources/com/hyundai/global/mapper/ManagerMapper.xml
Labels: feature, :1st_place_medal: 은구

#63 주석 및 코드 정리
  src/main/java/com/hyundai/domain/admin/controller/AdminBannerController.java
  src/main/java/com/hyundai/domain/admin/controller/AdminEventController.java
  src/main/java/com/hyundai/domain/admin/controller/AdminMemberController.java
  src/main/java/com/hyundai/domain/admin/controller/AdminProductController.java
  src/main/java/com/hyundai/domain/admin/service/AdminMemberService.java
  src/main/java/com/hyundai/domain/admin/service/AdminMemberServiceImpl.java
  src/main/java/com/hyundai/domain/utils/paging/Criteria.java
  src/main/java/com/hyundai/domain/utils/paging/PageDTO.java
  src/main/java/com/hyundai/global/config/S3Config.java
Labels: fix
